purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7893839138559997
  brandStrength: 0.4375
  lightness: 0.5982982330024242
  brandColors:
    - '#0A0A09'
    - '#B82020'
    - '#9E9787'
    - '#E84547'
    - '#F5BB8E'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Where the Wilde Things Are
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2905478
layout_spectrum: 0.5461869
