name: Where the Wilde Things Are
favicon: null
layout_spectrum: 0.8091785341966897
typography_spectrum: 0.20972481137141585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3806565550621599
  lightness: 0.5982982330024242
  saturation: 0.7893839138559997
  rhythmicContrast: 0.5611824786756188
purpose: []
